spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_session?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: localhost

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true